### PR TITLE
Update dot option definitions to latest (2015)

### PR DESCRIPTION
**Pull request by r0ckarong**
The rdot.rb file had outdated definitions for the available options. I've updated this to best of my knowledge. This addresses a comment from #61 

discussion https://github.com/monora/rgl/discussions/61#discussioncomment-1391967

Definitions taken from the linked 2015 version: https://www.graphviz.org/pdf/dotguide.pdf

### CODE REVIEW

**Comment by monora** [comment]
Thank you very much for your effort to add the "new" dot options. I hope you missed none ;-)
After merging #88 could be rebase this branch on top of it and add one test for one of the new options?

**Comment by r0ckarong** [comment]
> After merging #88 could you rebase this branch on top of it and add one test for one of the new options?

Of course.

**Comment by r0ckarong** [comment]
Rebased and added new test. Passing fine.

**Comment by r0ckarong** [comment]
I cherry-picked the relevant commits on a fresh copy of current master. Tests passing. I think we're good.

**Comment by r0ckarong** [comment]
> Do you think it is easy to have a test, which validates the output of `write_to_graphic_file`? Which tests one or two of the new attributes. That is define a fixture png file with a simple Graph with one edge and compare the output in the test.

I'm actually already working on a test that validates all node and edge options. I was planning to add this as another pull request because I will need some more time to define the proper examples that show the actual results of the options.

node-opts-graph

**Comment by monora** [comment]
> Maybe I can use the resulting SVG to compare against and see if the actual SVG tags are correct. If you know how to compare a fixture png to something the test produces I'm happy to learn how to do this.

Since I switched to python for day to day work, I am not firm with ruby test libraries. `pytest` is really good defining fixtures. But a simple file diff could also work.

**Comment by r0ckarong** [comment]
Do you have a pointer on how this would be done in Python?

**Comment by monora** [comment]
> Do you have a pointer on how this would be done in Python?

[About fixtures — pytest documentation](https://docs.pytest.org/en/7.1.x/explanation/fixtures.html)
[pytest-datadir · PyPI](https://pypi.org/project/pytest-datadir/)

This is what I would use in python

**Comment by r0ckarong** [comment]
Should he just initialize these in full so the user doesn't have to care? I
liked the freedom to pick those that I actually need but this is achieved
by just supplying to the set methods what you actually want.

**Comment by r0ckarong** [comment]
You need to set up the options hashes edge_options and vertex_options with
the procs like in the _complicated_options test. This is the application
side configuration for which attributes should be parsed.

```ruby
dg = RGL::DirectedAdjacencyGraph[1,2]
dg.set_vertex_options(1, shape: 'tab', fontcolor: 'blue')
dg.set_edge_options(1, 2, color: 'blue')

get_vertex_setting = proc { |v| graph.vertex_options[v] }
get_edge_setting = proc { |u, v| graph.edge_options[graph.edge_class.new(u, v)] }

vertex_options = {
'shape' => get_vertex_setting,
'fontcolor' => get_vertex_setting,
}

edge_options = {
'color' => get_edge_setting,
}

dot_options = { 'edge' => edge_options, 'vertex' => vertex_options }.to_s

dg.write_to_graphic_file(dot_options)
```

**Comment by r0ckarong** [comment]
This is proving harder than I thought. There is something wrong (or I don't get it) between the edge options assignemnt and the way dot reads it. I'm going to dig more.

**Comment by r0ckarong** [comment]
@monora 

The convenience thing for the settings is separate from this PR. Could we move forward with updating the dot option definitions. The provided test already covers the new options.

**Comment by monora** [comment]
> The convenience thing for the settings is separate from this PR. Could we move forward with updating the dot option definitions. The provided test already covers the new options.
>
OK. 
> Once I have more results for the exhaustive tests or the convenience improvement for the settings methods I'd add new PRs.

Can you file an issue or PR which describes the problem to be solved, so that we can refer to it in the release notes later.

Thereafter we can merge this PR.

**Comment by r0ckarong** [comment]
> Can you file an issue or PR which describes the problem to be solved, so that we can refer to it in the release notes later.

I have opened #92 and filed #91 [WIP].

I'm currently blocked with other work but I'll get back to this.

**Pull request closed without merging**
